# Generated by Django 5.1 on 2024-10-11 14:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_likedpost_post_id_alter_post_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='folowedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('follower', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8347cb11-6e8d-401e-bdb0-afcc318511c7'), primary_key=True, serialize=False),
        ),
    ]
