# Generated by Django 5.1 on 2024-10-11 15:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_post_id_alter_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8fdc1be2-1251-4dc3-a489-c5b9d2f199d6'), primary_key=True, serialize=False),
        ),
    ]
