# Generated by Django 5.1 on 2024-10-11 15:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d40bc9b5-7bf5-4d51-a356-43254f092bfb'), primary_key=True, serialize=False),
        ),
    ]
