# Generated by Django 5.1 on 2024-10-11 15:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_post_id_alter_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7f53c226-b0e5-4127-9a04-80a8cfe85a8a'), primary_key=True, serialize=False),
        ),
    ]
