# Generated by Django 5.1 on 2024-10-18 15:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_post_id_alter_post_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='commentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=100)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='likedpost',
            name='name_like',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='no_of_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('092cde1d-2ad3-4f0f-9d98-13728b29cf54'), primary_key=True, serialize=False),
        ),
    ]
