# Generated by Django 5.1 on 2024-10-18 15:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_commentpost_likedpost_name_like_post_no_of_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedpost',
            name='name_like',
        ),
        migrations.AddField(
            model_name='likedpost',
            name='type_of',
            field=models.CharField(default='like', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1de3349a-55d9-4e53-90d2-6dbc4e46d79b'), primary_key=True, serialize=False),
        ),
    ]
