# Generated by Django 5.1 on 2024-10-23 13:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_room_alter_post_id_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.CharField(default='toanle', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('231b3574-59fd-4fac-98ee-4bef0364b2a0'), primary_key=True, serialize=False),
        ),
    ]
